services:
  nginx:
    image: nginx
    volumes:
      - ./volumes/nginx-data:/etc/nginx
      - /etc/letsencrypt/live/francl.in:/etc/letsencrypt/live/francl.in:ro
      - /etc/letsencrypt/archive/francl.in:/etc/letsencrypt/archive/francl.in:ro
    networks:
      gateway:
        aliases:
          - gateway
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

networks:
  gateway:
    name: gateway
    attachable: true
    enable_ipv6: true
