name: Deployment Gateway

on:
  push:
    branches:
      - main

jobs:
  deployment:
    uses: fssou/gh-workflows/.github/workflows/reusable-deploy-docker-compose-with-ssh.yaml@main
    secrets:
      ssh_key: ${{ secrets.SSH_KEY }}
      ssh_host: ${{ secrets.SSH_HOST }}
    with:
      docker_compose_project_name: gateway
      docker_compose_volumes_folder: ${{ github.workspace }}/volumes
      destroy: false
